#!/bin/bash

# sudo /usr/bin/time -v bash /home/cwillu/work/dominos/reports/vm-builder
# sudo qemu -kernel-kqemu -net nic -net tap root.qcow2

mkdir /tmp/shm
mount -t tmpfs -o size=5G,mode=700 tmpfs /tmp/shm

NAME="dev-4"

rm -rf $NAME

ubuntu-vm-builder kvm hardy -d $NAME \
  -t /tmp/shm \
  --arch 'i386'  --mem '256'  --rootsize '4096'  --swapsize '1024'  \
  --kernel-flavour 'virtual'  --hostname $NAME  --domain 'cwillu.com'  \
  --mirror 'http://172.16.1.64:3142/ca.archive.ubuntu.com/ubuntu'  --components 'main,restricted,universe'  \
  --addpkg 'acpi acpid acpi-support anacron apmd avahi-autoipd avahi-daemon bc ca-certificates consolekit dc 
            gcc hal libnss-mdns make network-manager-gnome powernowd readahead screen unzip xdg-utils xterm zip 

            git-core openssh-server       

            python-docutils python-turbogears python-crypto             
           ' \
  --name 'Carey Underwood'  --user 'cwillu'  \
  --ssh-key ~/.ssh/id_rsa.pub \

umount -f /tmp/shm
rmdir /tmp/shm


